name: Verify

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    uses: cgranleese-r7/metasploit-framework/.github/workflows/shared_gem_verify.yml@add-gem-verify-shared-pipeline
